language: python
python:
  - 3.4
  - 3.5
  - 3.6

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.hypothesis
install:
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=matrox -m unittest discover
  - coverage report -m
after_success:
  - coveralls